Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-01, with the labels that each got.

#80 Move to shared ASP 2
  infrastructure/main.tf
Labels: ns:div-emca-pr-80

#82 DIV-3885 - set a separate timeout for health checks
  src/main/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplication.java
  src/main/java/uk/gov/hmcts/reform/emclient/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/EvidenceManagementStoreAPI.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/ServiceAuthProviderHealthCheck.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
Labels: ns:div-emca-pr-82

#81 Revert to normal ASP
  infrastructure/main.tf
Labels: ns:div-emca-pr-81
