Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-05, with the labels that each got.

#96 Point to SIDAM Demo
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:div-emca-pr-96

#99 Force more secure version on tomcat
  build.gradle
Labels: ns:div-emca-pr-99

#100 DIV-4835 Fix PMD/checkstyle warnings
  build.gradle
  ruleset.xml
Labels: ns:div-emca-pr-100

#101 convert application.properties to application.yml
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidatorTest.java
Labels: ns:div-emca-pr-101
