Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-10, with the labels that each got.

#126 Fix build and cleanup ase
  Dockerfile
  dependency-check-suppressions.xml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  lib/applicationinsights-agent-2.3.1.jar
Labels: ns:div-emca-pr-126

#128 DIV-5844 - Update ithc
  .gitignore
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  build.gradle
  charts/div-emca/Chart.yaml
  charts/div-emca/requirements.yaml
  charts/div-emca/values.aat.template.yaml
  charts/div-emca/values.preview.template.yaml
  charts/div-emca/values.yaml
  dependency-check-suppressions.xml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  lib/applicationinsights-agent-2.0.2.jar
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileDownloadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IDAMUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java
  src/integrationTest/resources/application-local.properties
  src/integrationTest/resources/example-application-local.properties
  src/main/java/uk/gov/hmcts/reform/emclient/insights/AppInsights.java
  src/main/resources/application.yml
  src/main/resources/example-application-aat.yml
  src/test/java/uk/gov/hmcts/reform/emclient/insights/AppInsightsTest.java
  web.config
Labels: ns:div-emca-pr-128

#131 DIV-5991: Removed some code smell
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/uk/gov/hmcts/reform/emclient/idam/api/IdamApiClient.java
  src/main/java/uk/gov/hmcts/reform/emclient/idam/services/UserService.java
  src/main/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidator.java
Labels: ns:div-emca-pr-131

#132 Updated minor dependency versions and removed unnecessary vuln suppressions
  build.gradle
  dependency-check-suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplication.java
  src/main/java/uk/gov/hmcts/reform/emclient/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/emclient/idam/models/UserDetails.java
  src/main/java/uk/gov/hmcts/reform/emclient/response/FileUploadResponse.java
  src/main/java/uk/gov/hmcts/reform/emclient/validation/constraint/EvidenceFile.java
  src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/controller/RootControllerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/BaseFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/EvidenceManagementDeleteFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/idam/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplUTest.java
Labels: ns:div-emca-pr-132

#133 Add dependabot config
  .dependabot/config.yml
Labels: ns:div-emca-pr-133

#143 Bump health starter
  build.gradle
Labels: ns:div-emca-pr-143
