Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-09, with the labels that each got.

#121 [PREVIEW] Changed to use CNP Module Webapp
  infrastructure/main.tf
Labels: ns:div-emca-pr-121

#122 DIV-5762 - use java chart v2.6.0 and reduced duplicated env references
  charts/div-emca/Chart.yaml
  charts/div-emca/requirements.yaml
  charts/div-emca/values.aat.template.yaml
  charts/div-emca/values.preview.template.yaml
  charts/div-emca/values.yaml
Labels: ns:div-emca-pr-122

#123 DIV-5762 - added disableLegacyDeployment() to Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:div-emca-pr-123

#125 DIV-5781: Address Jackson Databind vulnerabilities (CVE-2019-14540 and 16335)
  dependency-check-suppressions.xml
Labels: ns:div-emca-pr-125

#124 Delete application from ASE
  infrastructure/main.tf
Labels: ns:div-emca-pr-124
