Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-04, with the labels that each got.

#89 DIV-4458 Added download service
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileDownloadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/ResourceLoader.java
  src/integrationTest/resources/documents/testDocument.pdf
  src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
  src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadService.java
  src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplUTest.java
Labels: ns:div-emca-pr-89

#93 Add CVE-2018-1258 suppression
  dependency-check-suppressions.xml
Labels: ns:div-emca-pr-93

#95 Revert "Disable prod deployments"
  Jenkinsfile_CNP
Labels: ns:div-emca-pr-95

#94 DIV-3956 - reduced logging noise
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EMClientFileUploadTest.java
  src/main/java/uk/gov/hmcts/reform/emclient/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
  src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java
  src/test/resources/logback-test.xml
Labels: ns:div-emca-pr-94

#97 DIV-4520 helm chart
  Jenkinsfile_CNP
  build.gradle
  charts/div-emca/Chart.yaml
  charts/div-emca/requirements.yaml
  charts/div-emca/values.aat.template.yaml
  charts/div-emca/values.preview.template.yaml
  charts/div-emca/values.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  src/integrationTest/resources/application.properties
  src/kubernetes/config.aat.yaml
  src/kubernetes/deployment.template.yaml
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:div-emca-pr-97

#98 Enable swagger
  build.gradle
  src/main/java/uk/gov/hmcts/reform/emclient/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
  src/main/resources/application.properties
Labels: ns:div-emca-pr-98

#84 set up divorce emca security scan
  Jenkinsfile_nightly
  security.sh
Labels: ns:div-emca-pr-84
