Repository hmcts/div-evidence-management-client-api, pull requests merged in 2019-06, with the labels that each got.

#103 Set instance size to I3
  infrastructure/main.tf
Labels: ns:div-emca-pr-103

#104 Adjust instance size using variables
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-emca-pr-104

#102 DIV-4484 upgrade gradle version to 5.x
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplUTest.java
Labels: ns:div-emca-pr-102

#105 DIV-5059: OWASP upgrade
  build.gradle
Labels: ns:div-emca-pr-105

#106 DIV-3264: Update readmes
  LICENSE.md
  README.md
Labels: ns:div-emca-pr-106
