Repository hmcts/div-evidence-management-client-api, pull requests merged in 2020-01, with the labels that each got.

#161 fix zap python compatibility
  security.sh
Labels: ns:div-emca-pr-161

#163 Upgrade tomcat
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
Labels: ns:divorce, rel:div-emca-pr-163

#171 Moved dependabot to monthly and updated readme
  .dependabot/config.yml
  LICENSE.md
  README.md
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:divorce, rel:div-emca-pr-171

#172 FIX-Address CVE-2020-5398 and upgrade dependencies
  build.gradle
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/emclient/config/HttpConnectionConfiguration.java
Labels: ns:divorce, rel:div-emca-pr-172
