Repository hmcts/div-evidence-management-client-api, pull requests merged in 2022-05, with the labels that each got.

#377 patch for dep check and fix test outcome
  build.gradle
  charts/div-emca/Chart.yaml
  charts/div-emca/values.yaml
  dependency-check-suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
Labels: ns:divorce, prd:div, rel:div-emca-pr-377

#381 Bumping tomcat
  build.gradle
Labels: ns:divorce, prd:div, rel:div-emca-pr-381

#383 Bumping spring
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-emca-pr-383
