Repository hmcts/div-evidence-management-client-api, pull requests merged in 2022-08, with the labels that each got.

#394 DFR-1086 Update Readme
  README.md
Labels: ns:divorce, prd:div, rel:div-emca-pr-394

#395 Add backstage configuration file
  catalog-info.yaml
Labels: ns:divorce, prd:div, rel:div-emca-pr-395

#397 Fix functional tests
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java
  src/integrationTest/resources/application.properties
Labels: ns:divorce, prd:div, rel:div-emca-pr-397
