Repository hmcts/div-evidence-management-client-api, pull requests merged in 2024-05, with the labels that each got.

#443 DFR-2641-Upgrade to java 17 and tidy up health checks
  .github/renovate.json
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  charts/div-emca/Chart.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  package.json
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EmClientFileDownloadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EmClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementDeleteServiceImplUTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementDownloadServiceImplUTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/EvidenceManagementUploadServiceImplUTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/IntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/emclient/ServiceContextConfiguration.java
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/documents/testDocument.pdf
  src/main/java/uk/gov/hmcts/reform/emclient/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributes.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/ServiceAuthProviderHealthCheck.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/emclient/application/EvidenceManagementClientApplicationTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributesTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidatorTest.java
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-emca-pr-443, enable_keep_helm

#445 Fix Swagger configuration
  src/contractTest/resources/application.yml
Labels: ns:divorce, prd:div, rel:div-emca-pr-445

#446 Fix azure secrets configuration
  charts/div-emca/Chart.yaml
  charts/div-emca/values.yaml
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
Labels: ns:divorce, prd:div, rel:div-emca-pr-446

#447 Update state.tf azurerm to allow non-prod deploy
  infrastructure/state.tf
Labels: ns:divorce, prd:div, aat/no-changes, prod/no-changes, rel:div-emca-pr-447

#452 Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:divorce, prd:div, aat/no-changes, prod/no-changes, rel:div-emca-pr-452
